Address ERROR:
INFO: pip is looking at multiple versions of django-celery-results to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements_latest_version.txt (line 11) and celery because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested celery
    django-celery-results 1.1.2 depends on celery<5.0 and >=4.3
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts